
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IANIMAR = 7;
  public static final int RES = 13;
  public static final int SUM = 14;
  public static final int ICIRCULO = 2;
  public static final int animacion = 16;
  public static final int IRECTANGULO = 4;
  public static final int COMA = 10;
  public static final int digito = 17;
  public static final int EOF = 0;
  public static final int MULT = 12;
  public static final int DIV = 11;
  public static final int error = 1;
  public static final int color = 15;
  public static final int ILINEA = 5;
  public static final int PC = 9;
  public static final int IPOLIGONO = 6;
  public static final int PA = 8;
  public static final int ICUADRADO = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ICIRCULO",
  "ICUADRADO",
  "IRECTANGULO",
  "ILINEA",
  "IPOLIGONO",
  "IANIMAR",
  "PA",
  "PC",
  "COMA",
  "DIV",
  "MULT",
  "RES",
  "SUM",
  "color",
  "animacion",
  "digito"
  };
}

